[package]
name = "speach"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.23"
rustyline = "11.0.0"
stilo = "0.1.1"
tts = "0.25.0"
